name: ride_shared
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.3

dev_dependencies:
  ride_lints:
    path: ../lints
  test: ^1.25.0
