name: ride_shared
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  clock: ^1.1.1
  crypto: ^3.0.3

dev_dependencies:
  fake_async: ^1.3.1
  ride_lints:
    path: ../lints
  test: ^1.25.0
